apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: nuxeo-$NAME-cpu-hpa
spec:
  maxReplicas: 5
  minReplicas: 1
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 80
    type: Resource    
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nuxeo-$NAME-api
