{
 "title": "Tenants System Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "tenant2",
    "label": "Tenant",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "resource.label.cluster_name",
       "=",
       "multitenants",
       "AND",
       "resource.label.namespace_name",
       "=",
       "$tenant2"
      ],
      "groupBys": [],
      "metricKind": "CUMULATIVE",
      "metricType": "kubernetes.io/container/cpu/core_usage_time",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "jx-preprod",
      "unit": "s{CPU}",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "CPU  Limit utilisation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.cluster_name",
       "=",
       "multitenants",
       "AND",
       "resource.label.namespace_name",
       "=",
       "$tenant2"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/cpu/limit_utilization",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "jx-preprod",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Instances per tenant",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.namespace_name",
       "=",
       "$tenant2"
      ],
      "groupBys": [ "resource.label.namespace_name" ],
      "metricKind": "GAUGE",
      "metricType": "custom.googleapis.com/nuxeo/dropwizard5_nuxeo.instance-up_counter",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "jx-preprod",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Instances per tenant",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.namespace_name",
       "=",
       "$tenant2"
      ],
      "groupBys": [ "resource.label.namespace_name" ],
      "metricKind": "GAUGE",
      "metricType": "custom.googleapis.com/nuxeo/dropwizard5_nuxeo.instance-up_counter",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "jx-preprod",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Completed Works",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "metric.label.cluster_name",
       "=",
       "multitenants",
       "AND",
       "metric.label.namespace_name",
       "=",
       "$tenant2"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "custom.googleapis.com/nuxeo/dropwizard5_nuxeo.works.global.queue.completed_gauge",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "jx-preprod",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Async Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "metric.label.namespace_name",
       "=",
       "$tenant2"
      ],
      "groupBys": [ "metric.label.namespace_name" ],
      "metricKind": "GAUGE",
      "metricType": "custom.googleapis.com/nuxeo/dropwizard5_nuxeo.async.load_gauge",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "jx-preprod",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  }
 ]
}