{
 "title": "Usage Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "tenant",
    "label": "Tenant",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Blob Volume",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "metric.label.namespace_name",
       "=",
       "$tenant"
      ],
      "groupBys": [ "metric.label.namespace_name" ],
      "metricKind": "GAUGE",
      "metricType": "custom.googleapis.com/nuxeo/dropwizard5_nuxeo.statistics.repository.blobs.mainBlobs_gauge",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "jx-preprod",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    },
    {
     "metricQuery": { "projectName": "jx-preprod" },
     "sloQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "projectName": "jx-preprod",
      "selectorName": "select_slo_health",
      "serviceId": "",
      "sloId": ""
     }
    }
   ]
  },
  {
   "title": "Documents Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "metric.label.namespace_name",
       "=",
       "$tenant"
      ],
      "groupBys": [],
      "metricKind": "",
      "metricType": "custom.googleapis.com/nuxeo/dropwizard5_nuxeo.statistics.repository.documents_gauge",
      "perSeriesAligner": "",
      "projectName": "jx-preprod",
      "unit": "",
      "valueType": ""
     }
    },
    {
     "metricQuery": { "projectName": "jx-preprod" },
     "sloQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "projectName": "jx-preprod",
      "selectorName": "select_slo_health",
      "serviceId": "",
      "sloId": ""
     }
    }
   ]
  },
  {
   "title": "Document Count / Repartituon",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MAX",
      "filters": [
       "metric.label.namespace_name",
       "=",
       "$tenant"
      ],
      "groupBys": [ "metric.label.doctype" ],
      "metricKind": "",
      "metricType": "custom.googleapis.com/nuxeo/dropwizard5_nuxeo.statistics.repository.documents_gauge",
      "perSeriesAligner": "",
      "projectName": "jx-preprod",
      "unit": "",
      "valueType": ""
     }
    },
    {
     "metricQuery": { "projectName": "jx-preprod" },
     "sloQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "projectName": "jx-preprod",
      "selectorName": "select_slo_health",
      "serviceId": "",
      "sloId": ""
     }
    }
   ]
  },
  {
   "title": "Events over 1h",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "metric.label.namespace_name",
       "=",
       "$tenant"
      ],
      "groupBys": [ "metric.label.event" ],
      "metricKind": "",
      "metricType": "custom.googleapis.com/nuxeo/dropwizard5_nuxeo.statistics.audit.events_gauge",
      "perSeriesAligner": "",
      "projectName": "jx-preprod",
      "unit": "",
      "valueType": ""
     }
    },
    {
     "metricQuery": { "projectName": "jx-preprod" },
     "sloQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "projectName": "jx-preprod",
      "selectorName": "select_slo_health",
      "serviceId": "",
      "sloId": ""
     }
    }
   ]
  }
 ]
}