nameOverride: cncr1
architecture: single
replicaCount: 1
ingress:
  hostname: cncr1.multitenant.nuxeo.com
  tls: 
    - hosts:
      - cncr1.multitenant.nuxeo.com
      secretName: static-wildcard-tls
customProperties:
  tenant: |
    nuxeo.tenantId=company-a
    # k8s_pod vs k8s_container vs default
    nuxeo.stackdriver.forceResourceType=k8s_pod
    metrics.streams.enabled=true
extraVolumes:
  - name: gcpcconfig
    secret:
      secretName: cncr-cncr1-gcp-sa
