nameOverride: cncr4
architecture: single
replicaCount: 1
image:
  tag: latest-rest-api
ingress:
  hostname: cncr4.multitenant.nuxeo.com
  tls: 
    - hosts:
      - cncr4.multitenant.nuxeo.com
      secretName: static-wildcard-tls
