nameOverride: cncr2
architecture: api-worker
replicaCount: 2
workerCount: 1
ingress:
  hostname: cncr2.multitenant.nuxeo.com
  tls: 
    - hosts:
      - cncr2.multitenant.nuxeo.com
      secretName: static-wildcard-tls
customProperties:
  tenant: |
    nuxeo.tenantId=company-b
    # k8s_pod vs k8s_container vs default
    nuxeo.stackdriver.forceResourceType=k8s_pod
    metrics.streams.enabled=true
