packages: 
enable: true
architecture: singleNode
image:
  repository: gcr.io/jx-preprod/nuxeo-quarkus-jvm
enable: true
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/affinity-mode: persistent
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    kubernetes.io/ingress.class: "nginx"    
#    cert-manager.io/issuer: "letsencrypt-staging"
replicaCount: 2
workerCount: 1
metrics:
  enabled: true
  stackdriver:
    enabled: false
mongodb:
  enabled: true
  host: nuxeo-mongodb-headless.nx-shared-storage.svc.cluster.local
  url: nuxeo-mongodb-0.nuxeo-mongodb-headless.nx-shared-storage.svc.cluster.local:27017,nuxeo-mongodb-1.nuxeo-mongodb-headless.nx-shared-storage.svc.cluster.local:27017,nuxeo-mongodb-2.nuxeo-mongodb-headless.nx-shared-storage.svc.cluster.local:27017
  credentials: root:XvdhfCsW6j
elasticsearch:
  enabled: true
  host: elasticsearch-master.nx-shared-storage.svc.cluster.local
kafka:
  enabled: true
  host: nuxeo-kafka.nx-shared-storage.svc.cluster.local
amazonS3:
  enabled: true
  bucket: "nuxeo-multitenant-storage-bucket"
  awsAccessKeyId: $GCP_AWS_ACCESS_KEY_ID
  awsSecretKey: $GCP_AWS_SECRET_KEY
  